steps:
  - label: "Go build"
    agents:
      queue: "mac-xcode-2"
    artifact_paths:
      - "go-build-profile.gz"
    command: |
      bazelisk \
      build \
      --profile=go-build-profile.gz \
      -- \
      //go/...

  - label: "Go build (with caching)"
    agents:
      queue: "mac-xcode-2"
    artifact_paths:
      - "go-build-profile.gz"
    command: |
      curl -fsSL https://get.namespace.so/cloud/install.sh | sh -s -- --version 0.0.386
      nsc bazel cache setup --bazelrc=/tmp/bazel-cache.bazelrc
      bazelisk --bazelrc=/tmp/bazel-cache.bazelrc \
        build \
        --profile=go-build-profile.gz \
        -- \
        //go/...
